import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  styles: ['normal'],
  preload: true,
})

import { NextAuthProvider } from './Providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={poppins.className}>{children}</body>
      </NextAuthProvider>
    </html>
  )
}
